#!/bin/sh -x
cd $HOME

if [ -f .Xrdb ] ; then
    xrdb .Xrdb
fi

#xset b 100 440 100
#xset m 4 8
#xset s blank
#xset s 600 10
#xset fp+ tcp/octet.ipc.akita-u.ac.jp:7000

xmodmap .xmodmaprc

#if (xrdb -symbol | egrep COLOR) ; then
#    set pink goldenrod skyblue aquamarine cyan
#    shift `expr $$ % $#`
#    xsetroot -bitmap $HOME/.bitmaps/tacchan -bg $1
#fi
